function [H,C,G,B] = auto_swingDynamics(q1,q2,dq1,dq2,g,l1,l2,lc1,lc2,d2,m1,m2,I1,I2)
%AUTO_SWINGDYNAMICS
%    [H,C,G,B] = AUTO_SWINGDYNAMICS(Q1,Q2,DQ1,DQ2,G,L1,L2,LC1,LC2,D2,M1,M2,I1,I2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2018 23:04:14

t2 = lc2.^2;
t3 = m2.*t2;
t4 = cos(q2);
t5 = sin(q2);
t6 = l1.*lc2.*m2.*t4;
t7 = I2+t3+t6-d2.*lc2.*m2.*t5;
H = reshape([I1+I2+t3+d2.^2.*m2+l1.^2.*m2+lc1.^2.*m1-d2.*lc2.*m2.*t5.*2.0+l1.*lc2.*m2.*t4.*2.0,t7,t7,I2+t3],[2,2]);
if nargout > 1
    t8 = d2.*t4;
    t9 = l1.*t5;
    t10 = t8+t9;
    C = [-dq2.*lc2.*m2.*t10.*(dq1.*2.0+dq2);dq1.^2.*lc2.*m2.*t10];
end
if nargout > 2
    t11 = sin(q1);
    t12 = q1+q2;
    t13 = sin(t12);
    G = [g.*m2.*(l1.*t11+lc2.*t13-d2.*cos(q1))+g.*lc1.*m1.*t11;g.*lc2.*m2.*t13];
end
if nargout > 3
    B = [0.0;1.0];
end
