function [pc1,pc2,p1,p2,p3] = auto_swingKinematics(q1,q2,l1,l2,lc1,lc2,d2)
%AUTO_SWINGKINEMATICS
%    [PC1,PC2,P1,P2,P3] = AUTO_SWINGKINEMATICS(Q1,Q2,L1,L2,LC1,LC2,D2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2018 23:04:15

t2 = cos(q1);
t3 = sin(q1);
pc1 = [lc1.*t3;-lc1.*t2];
if nargout > 1
    t4 = q1+q2;
    t5 = l1.*t3;
    t6 = sin(t4);
    t7 = cos(t4);
    pc2 = [t5-d2.*t2+lc2.*t6;-d2.*t3-l1.*t2-lc2.*t7];
end
if nargout > 2
    p1 = [t5;-l1.*t2];
end
if nargout > 3
    p2 = [t5-d2.*t2+l2.*t6;-d2.*t3-l1.*t2-l2.*t7];
end
if nargout > 4
    p3 = [t5-d2.*t2;-d2.*t3-l1.*t2];
end
